<?php

namespace Database\Seeders;

use App\Models\Role;
use App\Models\Student;
use App\Models\Teacher;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        // Mengisi tabel roles
        DB::table('roles')->insert([
            ['id' => 1, 'name' => 'admin'],
            ['id' => 2, 'name' => 'teacher'],
            ['id' => 3, 'name' => 'student'],
            ['id' => 4, 'name' => 'user'],
            ['id' => 5, 'name' => 'cashier'],
        ]);

        $names = [
            'ALICIA LATHIFA',
            'HARIEF RAMADHAN',
            'DEZEL GHALY RADYATAMA',
            'KELLAN CATALEYA MAGHENS',
            'FAUZAN ABDILLAH',
            'ZAIM ARKAN',
            'MARWAH MARDHIAN PUTRI',
            'MICHELINE ANDREANI E SATOKO',
            'MARWAH AULIA PUTRI',
            'RADITYA WADI PRAYATA',
            'GEFRAN KASDIK',
            'SRI KHANZA SAKHI NAFIRA',
            'FAUZIL',
            'OLIVIA',
            'NADHIFA WINDY',
            'ZAHRA DEVITRA',
            'INDAH DEVITRA RAISSA',
            'THIFATUL MARDIYAH',
            'NAAILA FAZIA AQILAH',
            'SINTIYA ARYANI',
            'SKY CATHAL MEGHENS',
            'KEVIN SUNARDIANSYAH',
            'KENVIN FIORENZIE KIE',
            'NADIRA RAUDHATUL',
            'MUHAMMAD HABIBI',
            'STEFAN TAN',
            'NADHIRA KIANDRA ANAIA PUTRI',
            'AQILA MISHA SHAFANA',
            'ANNISA JIHAN ANINDITA',
            'NADINE ZHAHIRAH ISBILLAH',
            'DIVA HUMAIRAH',
            'MUHAMMAD SAYYID YUSUF',
            'MUHAMMMAD BINTANG RAMADHAN',
            'AZZAHRA SHIDQIA PUTRI',
            'RADISTI KHAIRA',
            'KURNIA AULIANDI',
            'RAISAH NADHIRA',
            'RAHMAN HAKIM',
            'HAFIZH PRATAYA',
            'ZILVA AUJI HARDIYAN',
            'SYAFA',
            'M ZIKRI',
            'M HAFIZHUL FURQAN',
            'REAN MANDALA PUTRA',
            'HAIKAL AGRA PRASETIA',
            'FADHIL FIRMANSYAH',
            'NAHDA ANINDITA',
            'KHADZIM FAWAZULFA',
            'M RAZIQ',
            'RIVA MARITZA',
            'DEVIS WALDINATA PUTRA',
            'JOVANO JUNIOR',
            'FADIL USMAN HAMIZAN',
            'MLADINSKA AL ARRASY',
            'ZAHRA FAIZA FITRIA',
            'ALIFA PUTRI OKTAVIANI',
            'MEISYA PUTRI AULIA',
            'FEBRIZIO ALGHAZALI ANDRIE',
            'KEVIN ARGANI RAFISQI',
            'NAOMI',
            'FAHRI PUTRA SARDI',
            'FATIN DWI UTAMA',
            'FARUQ MUFADHAL ZALLIA',
            'IBRAHIM AKMAL YUDISTIRA',
            'BENING AIRIN',
            'SHAFIA AMIRAH',
            'HAFIZAH LUTFIAH NEDISYA',
            'MAULIDAH SYAFITRI',
            'ATHALLAH MAULANA RAFIF',
            'NAURA FAIRUS ZALLIA',
            'MUHAMMAD HANAFI ALWIS',
            'Ghaitsa Zhahira Nazvar',
            'FAWAZZA KHAIRUNISWA',
            'LUTHVI FARABI HASIBUAN',
            'VIERZA TAUFAHATI',
            'HAURA SABTRINI',
            'NURMALISA SILVIANA',
            'ASSYIFA RAMADHANIA PUTRI',
            'ASYFA MAHARANI',
            'REISYA HANIFA',
            'OLIVIA NANDA MAHARANI',
            'ALIF AL RASYID',
            'IBRAHIM TSABIT EL EMIR',
            'ABDULLAH AZZAM EL EMIR',
            'AMELIA ERSYA',
            'ALIIFA GHAISANI SHATHIR',
            'M RAFFA DYAKSA',
            'DARA PUTRI SRI RAHAYU',
            'MUHAMMAD ALGHIFARI ANDRIE',
            'MUHAMMAD BHAKTI',
            'VIGO DWINATA PUTRA ALFAREZA',
            'SOFFI HARNUM',
            'FATHIAN RAFASYA MORIS',
            'ATHIFAH ARDEL ANAFITRI',
            'TARA RAMAISYA',
            'QAISARA IZZATI NAJLA',
            'QEENAN VRISNEXI',
            'PELANGI',
            'SAHRA APRIA PUTRI',
            'MUHAMMAD RIVAL TRI WENDY',
            'FAREL JULIAN FHARDI',
            'HAFIDH AKMAL',
            'IQRAM HANAFI SURBAKTI',
            'KHAICA DEWI',
            'ZAHRANA AQILA ZIKRA',
            'DAVINE FERNANDO',
            'ARSYILA SHEEZA GHASSANI',
            'ARDAFFA YAZID LIMANY',
            'LIDIA MAULANA',
            'TOMI',
            'LATIFA FADILA ISMA',
            'SYIFA ZULIYUS PUTRI',
            'FAIRUZ BIMA PRAKOSO',
            'ENJEL ARILIAN',
            'NEYLAN ASEVYA DINATA',
            'DINDA AISYAH HALJONI',
            'WAHIDAH FITRI AZIZI',
            'FEBRAN TRI NANDA ALVRISKI',
            'M NUR ALI AL JEFRI',
            'ZIKRA KHAIRULLAH',
            'RADITYA APRINOYA',
            'WIRDATUL JANNAH',
            'AZHARIYAH KHALIDA',
            'SHAFIRA FAJRIATI HAMZAH',
            'ANDINI PUTRI CANIAGO',
            'NADIA YUDISTIA',
            'DESI KARINA',
            'TASYAH AULYAH TANJUNG',
            'ANNISA HUSNI',
            'ADITIA OKTARIAN DESMA',
            'BELVANA LUTHFIA RYNATA',
            'SALMA JUNIANTI',
            'KHAINANZA RAMADHANI',
            'FAHIRA NAJLA',
            'AQILLA PUTRI RAMADHANI',
            'NABILA STEPHANIE',
            'AZKA IRFANA',
            'GENO MARSITO',
            'MEISYA PUTRI RAMADHANI',
            'NAZIFA NADA ASHARA',
            'MUHAMMAD ZIKA',
            'ZAHRA ARYA PUTRI',
            'KHAIRUNNISA SALSABILA A',
            'DIEVIA PUTRI YUSMANTRI',
            'QUEENANDITA SHAREEN ARSYILA',
            'AKYFA ANANDITA VARISHA',
            'ARFA NANDRA PRATAMA',
            'IKHWANNUL HANIF',
            'HANIFAH AULIA',
            'AQUEENA AMALIA ARUMI',
            'FAIZA RAYYANA ZHAFIRA',
            'WILSYA AZZAHRA RAHADI',
            'ALIF RAHMAN FADILAH',
            'ATHAR RAHID PRATAMA',
            'FARHAH NABILA',
            'MUHAMMAD RAFIF ALFAREZI',
            'VELZIO DARMA REDILOVA',
            'NADIRA GUSANTI RAMADHANI',
            'ALIKHA NAILA PUTRI ANEVI',
            'M ARIEF RAHMAN HAKIM',
            'ALIYA MUSTIKA SARI',
            'FATIMAH NURUL SAHARA',
            'SISKA WULANDARI',
            'NAZWA ATHAYA',
            'AMIRATUD DALILAH',
            'ANDINI HENDRI',
            'SATRIA RAMADHAN',
            'M AFFANDI',
            'AQIL RAZIQ JAZALI',
            'RAFAN FERITRA AL RABBANI',
            'MIKHAILA KHAIRUNNISA',
            'KIARA BILQIS ALEESYA',
            'AGHA RIADI',
            'AFTAR RIADI',
            'WILLIAM CANTONA',
            'RAEKHANVAZA ARDIAN BATU BARA',
            'FATHIA',
            'FALISHA SHANUM ADANI',
            'VANESHA JOSAN PUTRI',
            'ANINDYA ALFADILLAH',
            'ZAHIRA AFID',
            'DERLYA MANDAILINA HARAHAP',
            'ADELIA QHAIREEN RAMADHANI',
            'KYRANA FADHANTYA TALITA SAKTI',
            'GINA OKTAVIANI',
            'RISTARLA ADREENA NUGRAHA',
            'KHAIRA AGUSTIN M',
            'MUHAMMAD THARIQ',
            'AYUDIA RAMADHANI',
            'CANAYA ABITA SHANUM',
            'RISKY SAPUTRA',
            'FARID ANANDA',
            'FADIL PRATAMA',
            'ZAHRA LULU BAHIRA',
            'OLIVE PUTRI ALMEYZA',
            'AQILA SHAHIA DAVISA',
        ];

        $users = [];
        foreach ($names as $name) {
            $email = strtolower(str_replace(' ', '', str_replace('.', '', $name))) . '@gmail.com';
            $users[] = [
                'name' => $name,
                'email' => $email,
                'password' => Hash::make('password'),
                'created_at' => now(),
                'updated_at' => now(),
                'role_id' => 3,
            ];
        }

        DB::table('users')->insert($users);

        // Mengisi tabel users
        DB::table('users')->insert([
            [
                'name' => 'Admin',
                'email' => 'admin@gmail.com',
                'password' => Hash::make('password'),
                'role_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'viska',
                'email' => 'viska@gmail.com',
                'password' => Hash::make('password'),
                'role_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ratil',
                'email' => 'ratil@gmail.com',
                'password' => Hash::make('password'),
                'role_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'isti',
                'email' => 'isti@gmail.com',
                'password' => Hash::make('password'),
                'role_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'roni',
                'email' => 'roni@gmail.com',
                'password' => Hash::make('password'),
                'role_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Guru 1',
                'email' => 'guru1@example.com',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Guru 2',
                'email' => 'guru2@example.com',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Siswa 1',
                'email' => 'siswa1@example.com',
                'password' => Hash::make('password'),
                'role_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Siswa 2',
                'email' => 'siswa2@example.com',
                'password' => Hash::make('password'),
                'role_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Mengisi tabel teachers
        $teacher = Role::find(2);
        foreach($teacher->users as $user){
            Teacher::create([
                'user_id' => $user->id,
                'address' => '-',
                'phone' => '-',
            ]);
        }

        // Mengisi tabel students
        $student = Role::find(3);
        foreach($student->users as $user){
            Student::create([
                'user_id' => $user->id,
                'address' => '-',
                'phone' => '-',
                'cabang' => '-',
            ]);
        }
    }
}
